name: Documentions deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Deploy gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
      - run: (test -x $HOME/.cargo/bin/mdbook-linkcheck || cargo install mdbook-linkcheck)
      - run: mdbook build documents && mdbook test documents

      - name: get submodule
        run:  git submodule update --init --recursive --remote

      - name: install deps
        run: |
             sudo make -C ecli install-deps

      - name: install test deps
        run:  |
              make -C examples/tests install-deps
              make -C examples/tests install-wasm-clang

      - name: test build runners
        run:  |
              make -C examples

      - name: test examples
        run:  |
              make -C examples/tests test

      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './examples/bpftools'
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: ./documents/book/html