name: Build and test eunomia-cc on Ubuntu

on:
  push:
    branches: "*"
    paths:
      - "eunomia-cc/**"
      - ".github/**"
  pull_request:
    branches: "*"
    paths:
      - "eunomia-cc/**"
      - ".github/**"

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: get submodule
      run:  git submodule update --init --recursive

    - name: install deps
      run: |
          sudo make -C eunomia-cc install-deps

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true

    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: build ecc
      run:  cd eunomia-cc && make && make install

    - name: test ecc
      run:  cd eunomia-cc/cmd && cargo test
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
        RUSTDOCFLAGS: '-Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

    - name: rust-grcov
      # You may pin to the exact commit or the version.
      # uses: actions-rs/grcov@bb47b1ed7883a1502fa6875d562727ace2511248
      uses: actions-rs/grcov@v0.1.5
      working-directory: eunomia-cc/cmd/

    - name: Install required cargo
      run: cargo install clippy-sarif sarif-fmt

    - name: Run rust-clippy
      run:
          cd eunomia-cc/cmd &&
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      continue-on-error: true

    - name: Run fmt check
      run:
          cd eunomia-cc/cmd && cargo fmt --check
    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: eunomia-cc/cmd/rust-clippy-results.sarif
        wait-for-processing: true

    - name: Code coverage using Codecov
      run: bash <(curl -s https://codecov.io/bash)

